### ISSUE TITLE
Commit a05e4a1 breaks existing clients

### ISSUE THREAD

**Issue by triggerNZ** [CommBank/permafrost#14]
I haven't had a chance to look deeper into this, but:

```
Hdfs.files(conf.outputBasePath.toPath, "*/*/*")
```
Now returns no files where it used to succeed

**Comment by rowandavies** [comment]
@triggerNZ Do you have a full example demonstrating this issue?  
Also, I can't click on a05e4a11c6 in the title so I've repeated it here.

**Comment by triggerNZ** [comment]
@rowandavies I will have to put together a test case demonstrating it, which is nontrivial, since it involves setting up test data. I will try to do that, but the code that failed is:

```
/** Method to get the list of all dates from the list of partitions,
    * which is based on year, month and day
    */
  def getDatesOfAllPartitions(baseLoc: String): Hdfs[List[DateTime]] = {
    val dateR = """year=(\d\d\d\d)/month=(\d\d)/day=(\d\d)$""".r.unanchored
    for {
                   /** Make directory if it doesn't exist
                     * a control happens here, if the path doesn't exist
                     */
      _          <- Hdfs.mkdirs(baseLoc.toPath)
      partitions <- files(baseLoc.toPath, "*/*/*")

      dates       = partitions.foldLeft(List[String]())((l, p) => p.toString match {
                      case dateR(yyyy, mm, dd) => s"$yyyy-$mm-$dd" :: l
                      case _                   => l
                    }).sorted
    } yield dates.map(_.toDate())
  }
```

`partitions` is empty since the change was introduced. Using the old code produces the files in those directories.

**Comment by rowandavies** [comment]
@triggerNZ Okay - I can see what happened.  The spec for the original version was interpreted more narrowly when the change was made.  I'll fix it now.

**Comment by rowandavies** [comment]
@triggerNZ Update: I'm working on this, and I've also added a recursive variant that returns a stream to avoid another issue.  I just need to add some appropriate tests.

**Comment by maxmithun** [comment]
In Farlo CLM also we are experiencing the issue after the upgrade to util-etl  version to `1.14.1-20150703071108-fb2a434` 

We used the `Hdfs.glob((conf.outputBasePath+"*/*/*").toPath)` functionality for the time being.

**Comment by dkristian** [comment]
Just ran into this problem myself - thanks for the tip about the work-around @maxmithun !

**Comment by stephanh** [comment]
Unless anyone disagrees or has a different opinion, I'm inclined to say that `files` will only support globs for the immediate directory otherwise the recursive case will be quite complex and I don't really want different behaviour for the recursive and non recursive case.

The `glob` function supports arbitrary globs.

Sorry about the backwards incompatible change.

**Comment by vineethvarghese** [comment]
The glob argument is a string. So how do you propose to restrict that?

Why not leave the `file` method as it was and provide a separate methods with the recursion but doesn't take it a glob string?

**Comment by stephanh** [comment]
@vineethvarghese we can't restrict that just add an assertion to check it at runtime.

The recursive files method should still use a glob so that we can restrict what kind of files we get back.

Doesn't it seem redundant to have a `files(dir, glob)` which is identical to `glob(new Path(dir, glob))`?

**Comment by vineethvarghese** [comment]
Saw your PR. Agree to your point. 

However, with this change we can't check a pattern say 3 levels down with `*/*/*/mas*`. Whether this is a valid search to be made is an entirely different question :).

**Comment by rowandavies** [comment]
(Was just looking here to reassign this, it seems @stephanh read my mind.)

I'd agree with the change, but the backwards breaking aspect seems worth considering.  I've heard of half a dozen situations where this issue affected code and required a swap to `glob`, so there are probably many more lurking in our codebase.  

But, if there's a runtime check that fails instead of just failing to find files, this should be fine, particularly if the failure message recommends using `glob` instead.

**Comment by rowandavies** [comment]
@vineethvarghese You can check 3 levels down using `glob` with `*/*/*/mas*` right?  

If we want to combine recursive traversal with globs, I'd suggest that it's unclear exactly how the two aspects should interact (e.g., what sorting and uniqueness).   If we really want to support this we should probably instead provide the recursive traversal via a corresponding method `dirs`.  Then the result from `dirs` could have `glob` mapped over it with the precise details chosen depending on the situation.

**Comment by vineethvarghese** [comment]
Ok `glob` will.

**Comment by stephanh** [comment]
I also added a `glob(root: Path, pattern: String)` in the PR so that the use is mostly the same as well.

Unless anyone else objects. I'm going to merge that PR and thereby close this issue.
